{
 "title": "Minecraft Servers",
 "tags": [ "gsdeploy" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_status_healthy",
     "legendFormat": "{{server_name}} {{instance}} {{server_version}}"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_status_players_online_count",
     "legendFormat": "{{server_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Max Players",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_status_players_max_count",
     "legendFormat": "{{server_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Server Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "minecraft_status_response_time_seconds",
     "legendFormat": "{{server_name}} {{instance}}"
    }
   ]
  }
 ]
}